### ISSUE TITLE
Trigonometric functions

### ISSUE THREAD

**Issue by vanyaahuja** [AdityaRoy999/Advance-Calc-in-python#4]
What's the use of input of two numbers in trigonometric functions?
The calculator is not providing the correct solution for trigonometric functions

**Comment by AdityaRoy999** [comment]
Two numbers is inputted in trigonometric functions so that the user can find the different values of two different numbers at same time is he wish to 
For the trigonometric functions make sure the number you have inputted is inside the domain else it will raise MathDomainError
IF YOU HAVE ANY OTHER ISSUES PLEASE FEEL FREE TO COMMENT
